[0m18:07:33.195334 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056298e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e27ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10615cec0>]}


============================== 18:07:33.202834 | 257a7048-0e41-4cc5-b237-e4a963cb4a7b ==============================
[0m18:07:33.202834 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:07:33.203664 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/stanislas/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m18:08:12.560564 [debug] [MainThread]: Starter project path: /Users/stanislas/Projets/dbt_Luxury/my_dbt_luxury/lib/python3.12/site-packages/dbt/include/starter_project
[0m18:08:12.576411 [info ] [MainThread]: 
Your new dbt project "dbt_Luxury" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:08:12.577113 [info ] [MainThread]: Setting up your profile.
[0m18:11:53.246747 [info ] [MainThread]: Profile dbt_Luxury written to /Users/stanislas/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:11:53.268991 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 260.21033, "process_in_blocks": "0", "process_kernel_time": 0.310381, "process_mem_max_rss": "102055936", "process_out_blocks": "0", "process_user_time": 1.72044}
[0m18:11:53.271010 [debug] [MainThread]: Command `dbt init` succeeded at 18:11:53.270078 after 260.21 seconds
[0m18:11:53.274802 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10615d0d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105d96480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056298e0>]}
[0m18:11:53.275794 [debug] [MainThread]: Flushing usage events
[0m18:11:53.678894 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:12:04.498015 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10be67f20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bff0fb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bff0d70>]}


============================== 18:12:04.506774 | 7be4b21e-8d94-4fcf-8245-3a365a828e82 ==============================
[0m18:12:04.506774 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:12:04.507643 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/stanislas/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:12:04.541581 [info ] [MainThread]: dbt version: 1.9.3
[0m18:12:04.542199 [info ] [MainThread]: python version: 3.12.4
[0m18:12:04.542635 [info ] [MainThread]: python path: /Users/stanislas/Projets/dbt_Luxury/my_dbt_luxury/bin/python3.12
[0m18:12:04.543059 [info ] [MainThread]: os info: macOS-15.3.1-x86_64-i386-64bit
[0m18:12:05.032993 [info ] [MainThread]: Using profiles dir at /Users/stanislas/.dbt
[0m18:12:05.034350 [info ] [MainThread]: Using profiles.yml file at /Users/stanislas/.dbt/profiles.yml
[0m18:12:05.035075 [info ] [MainThread]: Using dbt_project.yml file at /Users/stanislas/Projets/dbt_Luxury/dbt_project.yml
[0m18:12:05.035532 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m18:12:05.037250 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.6810361, "process_in_blocks": "0", "process_kernel_time": 0.515801, "process_mem_max_rss": "103854080", "process_out_blocks": "0", "process_user_time": 2.156805}
[0m18:12:05.037806 [debug] [MainThread]: Command `dbt debug` failed at 18:12:05.037670 after 0.68 seconds
[0m18:12:05.040683 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bff0fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c19a930>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bf9a0f0>]}
[0m18:12:05.041457 [debug] [MainThread]: Flushing usage events
[0m18:12:05.402950 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:34:01.967230 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f967da0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ead0aa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f9d54c0>]}


============================== 16:34:01.976589 | 90ab43b9-b426-42d8-915d-d59ad24d408b ==============================
[0m16:34:01.976589 [info ] [MainThread]: Running with dbt=1.9.3
[0m16:34:01.977543 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/stanislas/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:34:01.978283 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/stanislas/Projets/dbt_Luxury/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:34:01.981501 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.16185014, "process_in_blocks": "0", "process_kernel_time": 0.449788, "process_mem_max_rss": "86208512", "process_out_blocks": "0", "process_user_time": 1.883339}
[0m16:34:01.982337 [debug] [MainThread]: Command `dbt run` failed at 16:34:01.982166 after 0.16 seconds
[0m16:34:01.982921 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f674da0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f6ddcd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f967710>]}
[0m16:34:01.983890 [debug] [MainThread]: Flushing usage events
[0m16:34:02.380061 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:34:43.464990 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109873890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109d5d6a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109d5d460>]}


============================== 16:34:43.473631 | 3c4cb91b-6fd2-4b9f-b2c8-e873c26e3d9a ==============================
[0m16:34:43.473631 [info ] [MainThread]: Running with dbt=1.9.3
[0m16:34:43.474508 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/stanislas/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:34:43.475236 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/stanislas/Projets/dbt_Luxury/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:34:43.478431 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.14869381, "process_in_blocks": "0", "process_kernel_time": 0.394886, "process_mem_max_rss": "85921792", "process_out_blocks": "0", "process_user_time": 1.847972}
[0m16:34:43.479312 [debug] [MainThread]: Command `dbt run` failed at 16:34:43.479121 after 0.15 seconds
[0m16:34:43.479901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109ce3740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f6cc80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f6f620>]}
[0m16:34:43.480450 [debug] [MainThread]: Flushing usage events
[0m16:34:43.845770 [debug] [MainThread]: An error was encountered while trying to flush usage events
